### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '@@'

### ISSUE THREAD

**Issue by Kadasiddha** [adelosa/mciutil#39]
Hi adelosa,

I am facing following issue while extracting the IPM file.

Traceback (most recent call last):
  File "/usr/local/bin/mideu", line 11, in <module>
    sys.exit(cli_entry())
  File "/usr/local/lib/python2.7/site-packages/mciutil/cli/mideu.py", line 27, in cli_entry
    _main(args)
  File "/usr/local/lib/python2.7/site-packages/mciutil/cli/mideu.py", line 53, in _main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/mciutil/cli/convert.py", line 49, in convert_command
    ) for record in input_data
  File "/usr/local/lib/python2.7/site-packages/mciutil/mciutil.py", line 178, in flip_message_encoding
    source_format)
  File "/usr/local/lib/python2.7/site-packages/mciutil/mciutil.py", line 225, in _flip_element_encoding
    field_length = int(field_length_string)
ValueError: invalid literal for int() with base 10: '@@'

Can you please let me know where I am going wrong?
I have attached the ipm file below.

[mcsample1.ipm.txt](https://github.com/adelosa/mciutil/files/605943/mcsample1.ipm.txt)

**Comment by adelosa** [comment]
Most likely an issue with a bad record length or structure issue.. Use hexdump -C to isolate the part of the file experiencing the issue to ensure that its reading the records correctly. Provide details of just that record and where you think the tool is not working correctly.

**Comment by Kadasiddha** [comment]
The issue was related to the record length. Thanks!!! Adelosa
